#pragma once
#include "inttypes.h"

#define OCT_ID_NULL 0

typedef uint64_t OCT_ID;
typedef struct OCT_handle OCT_handle;

typedef enum {
    // letters
    OCT_KEY_A, OCT_KEY_B, OCT_KEY_C, OCT_KEY_D, OCT_KEY_E,
    OCT_KEY_F, OCT_KEY_G, OCT_KEY_H, OCT_KEY_I, OCT_KEY_J,
    OCT_KEY_K, OCT_KEY_L, OCT_KEY_M, OCT_KEY_N, OCT_KEY_O,
    OCT_KEY_P, OCT_KEY_Q, OCT_KEY_R, OCT_KEY_S, OCT_KEY_T,
    OCT_KEY_U, OCT_KEY_V, OCT_KEY_W, OCT_KEY_X, OCT_KEY_Y,
    OCT_KEY_Z,

    // numbers
    OCT_KEY_0, OCT_KEY_1, OCT_KEY_2, OCT_KEY_3, OCT_KEY_4,
    OCT_KEY_5, OCT_KEY_6, OCT_KEY_7, OCT_KEY_8, OCT_KEY_9,

    // function keys
    OCT_KEY_F1, OCT_KEY_F2, OCT_KEY_F3, OCT_KEY_F4,
    OCT_KEY_F5, OCT_KEY_F6, OCT_KEY_F7, OCT_KEY_F8,
    OCT_KEY_F9, OCT_KEY_F10, OCT_KEY_F11, OCT_KEY_F12,

    // navigation
    OCT_KEY_UP, OCT_KEY_DOWN, OCT_KEY_LEFT, OCT_KEY_RIGHT,
    OCT_KEY_HOME, OCT_KEY_END, OCT_KEY_PAGE_UP, OCT_KEY_PAGE_DOWN,
    OCT_KEY_INSERT, OCT_KEY_DELETE,

    // modifiers
    OCT_KEY_LEFT_SHIFT, OCT_KEY_RIGHT_SHIFT,
    OCT_KEY_LEFT_CTRL, OCT_KEY_RIGHT_CTRL,
    OCT_KEY_LEFT_ALT, OCT_KEY_RIGHT_ALT,
    OCT_KEY_LEFT_SUPER, OCT_KEY_RIGHT_SUPER,
    OCT_KEY_CAPS_LOCK, OCT_KEY_NUM_LOCK, OCT_KEY_SCROLL_LOCK,

    // whitespace and editing
    OCT_KEY_SPACE, OCT_KEY_ENTER, OCT_KEY_BACKSPACE,
    OCT_KEY_TAB, OCT_KEY_ESCAPE,

    // punctuation
    OCT_KEY_APOSTROPHE,    // '
    OCT_KEY_COMMA,         // ,
    OCT_KEY_MINUS,         // -
    OCT_KEY_PERIOD,        // .
    OCT_KEY_SLASH,         // /
    OCT_KEY_SEMICOLON,     // ;
    OCT_KEY_EQUAL,         // =
    OCT_KEY_LEFT_BRACKET,  // [
    OCT_KEY_BACKSLASH,     // '\'
    OCT_KEY_RIGHT_BRACKET, // ]
    OCT_KEY_GRAVE,         // `

    // numpad
    OCT_KEY_NP_0, OCT_KEY_NP_1, OCT_KEY_NP_2, OCT_KEY_NP_3, OCT_KEY_NP_4,
    OCT_KEY_NP_5, OCT_KEY_NP_6, OCT_KEY_NP_7, OCT_KEY_NP_8, OCT_KEY_NP_9,
    OCT_KEY_NP_DECIMAL, OCT_KEY_NP_DIVIDE, OCT_KEY_NP_MULTIPLY,
    OCT_KEY_NP_SUBTRACT, OCT_KEY_NP_ADD, OCT_KEY_NP_ENTER,

    // mouse buttons
    OCT_KEY_MOUSE_LEFT, OCT_KEY_MOUSE_RIGHT, OCT_KEY_MOUSE_MIDDLE,
	OCT_KEY_MOUSE_4, OCT_KEY_MOUSE_5,

    OCT_KEYS_TOTAL
} OCT_key;

